### PR TITLE
Adding a new resource for cohort requests

### PR DESCRIPTION
**Pull request by sashipamo**
https://wiki.openmrs.org/display/docs/Proposal+after+Design+Forum+June+12,+2013

### CODE REVIEW

**Comment by dkayiwa** [comment]
@sashipamo should we close this too? And the many others below it? :)

**Comment by sashipamo** [comment]
Hi Daniel,

Sadly, yes :) . All should be outdated by now.

**Comment by dkayiwa** [comment]
I can see the sadness. :)
I wish i did not have to close them.
@sashipamo do you think this is a result of us taking too long (if not forgetting) to review these pull requests? In other words, what should we have done better to prevent all these efforts being wasted?

**Comment by sashipamo** [comment]
Hi Daniel,

Honestly speaking yes. This pull requests are relating to 2013 gsoc
project. I completed the project only upto mid evaluation. But i could have
done the necessary changes and get merge them with the master if some
responsible person(I know you don't  directly work with this repo) reviewed
it even after that.

But I don't think now these changes are valid and I am really out of touch
with this repo now :)

Thanks!

**Comment by sashipamo** [comment]
"what should we have done better to prevent all these efforts being wasted"

I think every repo has few special people who takes care about the repo.
And I can gurantee that I've informed the responsible person after creating
these pull reqs. I think those responsible persons should check whether
there is any open pull reqs. And ping them like this.

Just said coz you ask me a suggestion :) . I know most of people follow
this.

**Comment by dkayiwa** [comment]
Oh am please so sorry! I share the blame because it is my responsibility to oversee contributions like these. In case am not able to review, i should at least ping some one else to do the needful.
Sad though it feels, at least it has been a good practical lesson for me to ensure that it never happens again!

By the way, if i promised to review or at least watch closely by pinging someone else to review in a reasonable amount of time, do you still have the time to finish the work in these pull requests? :)

**Comment by sashipamo** [comment]
It's not your fault :) . I also lost the interest of it after that. Or else
I could have ping from my side.

These days, I am busy with gsoc works. May be after it finished I'll try to
find the time and contribute to this. But it will take around 3 more
months.

**Comment by dkayiwa** [comment]
Ok thanks! :)

**Comment by dkayiwa** [comment]
Closing because it is outdated?

**Pull request closed without merging**
